[tools]
deno = "latest"
usage = "latest"
# Node
node = "latest"
"npm:bash-language-server" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@vlabo/cspell-lsp" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
# Rust
rust = "latest"
"cargo:jinja-lsp" = "latest"
"cargo:harper-ls" = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[settings.python]
compile = false
